language: cpp

services:
  - docker

branches:
  only:
    - master
    - /v\d+\.\d+.*/

env:
  - DOCKER_IMAGE=knapsu/openxcom-build:trusty
  - DOCKER_IMAGE=knapsu/openxcom-build-x86:trusty DOCKER_EXEC="linux32 --"

before_script:
  - docker pull ${DOCKER_IMAGE}
  - env | grep -E "^TRAVIS|^DOCKER" > travis.env
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/openxcom --workdir /openxcom --env-file travis.env --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - docker exec -t builder ${DOCKER_EXEC} bash -c "echo -e '[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = ${TRANSIFEX_USER}\npassword = ${TRANSIFEX_PASSWORD}' > /root/.transifexrc"
  - docker exec -t builder ${DOCKER_EXEC} ./scripts/build.sh
  - ./scripts/upload.sh --sftp

after_script:
  - docker stop builder

cache:
  directories:
  - cache
