language: cpp

services:
  - docker

env:
  - ARCH=x86_64 DOCKER_IMAGE=knapsu/openxcom-build:latest DOCKER_EXEC=""
  - ARCH=i686 DOCKER_IMAGE=knapsu/openxcom-build-x86:latest DOCKER_EXEC="linux32 --"

before_script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -t -d --privileged --device /dev/fuse --volume ${TRAVIS_BUILD_DIR}:/openxcom -w /openxcom --name builder ${DOCKER_IMAGE}

script:
  - docker exec -t builder ${DOCKER_EXEC} ./scripts/build.sh
  - docker exec -t builder ${DOCKER_EXEC} ls -l --color /openxcom/*.AppImage

after_script:
  - docker stop builder
