language: cpp

services:
  - docker

branches:
  only:
    - master
    - /v\d+\.\d+.*/

env:
  - ARCH=x86_64 DOCKER_IMAGE=knapsu/openxcom-build:latest DOCKER_EXEC=""
  - ARCH=i686 DOCKER_IMAGE=knapsu/openxcom-build-x86:latest DOCKER_EXEC="linux32 --"

before_script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -t -d --volume ${TRAVIS_BUILD_DIR}:/openxcom -w /openxcom --name builder --device /dev/fuse --privileged ${DOCKER_IMAGE}

script:
  - docker exec -t builder ${DOCKER_EXEC} sh -c "echo '[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = ${TRANSIFEX_USER}\npassword = ${TRANSIFEX_PASSWORD}' > /root/.transifexrc"
  - docker exec -t builder ${DOCKER_EXEC} ./scripts/build.sh
  - ./scripts/upload.sh --transfer --scp

after_script:
  - docker stop builder

cache:
  directories:
  - commit-hash
