language: cpp

services:
  - docker

branches:
  only:
    - master

env:
  - ARCH=x86_64 DOCKER_IMAGE=knapsu/openxcom-build:latest DOCKER_EXEC=""
  - ARCH=i686 DOCKER_IMAGE=knapsu/openxcom-build-x86:latest DOCKER_EXEC="linux32 --"

before_script:
  - docker pull ${DOCKER_IMAGE}
  - docker run -t -d --privileged --device /dev/fuse --volume ${TRAVIS_BUILD_DIR}:/openxcom -w /openxcom --name builder ${DOCKER_IMAGE}

script:
  - docker exec -t builder ${DOCKER_EXEC} sh -c "echo '[https://www.transifex.com]\nhostname = https://www.transifex.com\nusername = ${TRANSIFEX_USER}\npassword = ${TRANSIFEX_PASSWORD}' > /root/.transifexrc"
  - docker exec -t builder ${DOCKER_EXEC} ./scripts/build.sh
  - sha1sum *.AppImage

after_script:
  - docker stop builder

after_success:
  - ./scripts/upload.sh *.AppImage
